//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.iOS.Business.BusinessLogics.MDM_Profile.BankIslamEn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MDM_Restriction_Menu
    {
        [Key]
        public System.Guid RID { get; set; }
        public string RestrictionName { get; set; }
        public string RestrictionDesc { get; set; }
        public Nullable<int> Queue { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> RGroup { get; set; }
        public Nullable<int> GroupHeader { get; set; }
        public Nullable<int> NumberType { get; set; }
        public Nullable<int> Partition { get; set; }
    }
}
