//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.iOS.Business.BusinessLogics.MDM_Profile.BankIslamEn
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDM_Profile_LDAP_SearchSettings
    {
        public System.Guid Profile_LDAP_ID { get; set; }
        public string Description { get; set; }
        public string Scope { get; set; }
        public string SearchBase { get; set; }
        public System.Guid ID { get; set; }
    }
}
