//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.iOS.Business.BusinessLogics.MDM_Profile.BankIslamEn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MDM_HttpProxy
    {
        [Key]
        public Guid Profile_ID { get; set; }
        [StringLength(50)]
        public string ProxyType { get; set; }
        [StringLength(50)]
        public string ProxyServer { get; set; }
        [StringLength(50)]
        public string Port { get; set; }
        [StringLength(50)]
        public string Username { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        [StringLength(50)]
        public string AllowByPassingProxy { get; set; }
    }
}
