//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.iOS.Business.BusinessLogics.MDM_Profile.BankIslamEn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User_Branch
    {
        [Key]
        public System.Guid bID { get; set; }
        public string bDesc { get; set; }
        public Nullable<int> bStatus { get; set; }
        public Nullable<bool> bMonday { get; set; }
        public Nullable<bool> bTuesday { get; set; }
        public Nullable<bool> bWednesday { get; set; }
        public Nullable<bool> bThursday { get; set; }
        public Nullable<bool> bFriday { get; set; }
        public Nullable<bool> bSaturday { get; set; }
        public Nullable<bool> bSunday { get; set; }
        public Nullable<System.TimeSpan> bOpenTime { get; set; }
        public Nullable<System.TimeSpan> bCloseTime { get; set; }
        public Nullable<System.DateTime> bCreatedDate { get; set; }
        public Nullable<System.DateTime> bApprovedDate { get; set; }
        public Nullable<System.DateTime> bDeclinedDate { get; set; }
        public Nullable<System.DateTime> bUpdatedDate { get; set; }
        public Nullable<System.Guid> bCreatedBy { get; set; }
        public Nullable<System.Guid> bApprovedBy { get; set; }
        public Nullable<System.Guid> bDeclinedBy { get; set; }
        public Nullable<System.Guid> bUpdatedBy { get; set; }
    }
}
