//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDMWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MDMWebService.MDMWebServiceSoap")]
    public interface MDMWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AndroidEnrollment", ReplyAction="*")]
        System.Threading.Tasks.Task<MDMWebService.AndroidEnrollmentResponse> AndroidEnrollmentAsync(MDMWebService.AndroidEnrollmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AndroidDeviceInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<MDMWebService.AndroidDeviceInfoResponse> AndroidDeviceInfoAsync(MDMWebService.AndroidDeviceInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AndroidEnrollmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AndroidEnrollment", Namespace="http://tempuri.org/", Order=0)]
        public MDMWebService.AndroidEnrollmentRequestBody Body;
        
        public AndroidEnrollmentRequest()
        {
        }
        
        public AndroidEnrollmentRequest(MDMWebService.AndroidEnrollmentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AndroidEnrollmentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sContent;
        
        public AndroidEnrollmentRequestBody()
        {
        }
        
        public AndroidEnrollmentRequestBody(string sContent)
        {
            this.sContent = sContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AndroidEnrollmentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AndroidEnrollmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public MDMWebService.AndroidEnrollmentResponseBody Body;
        
        public AndroidEnrollmentResponse()
        {
        }
        
        public AndroidEnrollmentResponse(MDMWebService.AndroidEnrollmentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AndroidEnrollmentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AndroidEnrollmentResult;
        
        public AndroidEnrollmentResponseBody()
        {
        }
        
        public AndroidEnrollmentResponseBody(string AndroidEnrollmentResult)
        {
            this.AndroidEnrollmentResult = AndroidEnrollmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AndroidDeviceInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AndroidDeviceInfo", Namespace="http://tempuri.org/", Order=0)]
        public MDMWebService.AndroidDeviceInfoRequestBody Body;
        
        public AndroidDeviceInfoRequest()
        {
        }
        
        public AndroidDeviceInfoRequest(MDMWebService.AndroidDeviceInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AndroidDeviceInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sContent;
        
        public AndroidDeviceInfoRequestBody()
        {
        }
        
        public AndroidDeviceInfoRequestBody(string sContent)
        {
            this.sContent = sContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AndroidDeviceInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AndroidDeviceInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public MDMWebService.AndroidDeviceInfoResponseBody Body;
        
        public AndroidDeviceInfoResponse()
        {
        }
        
        public AndroidDeviceInfoResponse(MDMWebService.AndroidDeviceInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AndroidDeviceInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AndroidDeviceInfoResult;
        
        public AndroidDeviceInfoResponseBody()
        {
        }
        
        public AndroidDeviceInfoResponseBody(string AndroidDeviceInfoResult)
        {
            this.AndroidDeviceInfoResult = AndroidDeviceInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface MDMWebServiceSoapChannel : MDMWebService.MDMWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class MDMWebServiceSoapClient : System.ServiceModel.ClientBase<MDMWebService.MDMWebServiceSoap>, MDMWebService.MDMWebServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MDMWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MDMWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), MDMWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MDMWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MDMWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MDMWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MDMWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MDMWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MDMWebService.AndroidEnrollmentResponse> MDMWebService.MDMWebServiceSoap.AndroidEnrollmentAsync(MDMWebService.AndroidEnrollmentRequest request)
        {
            return base.Channel.AndroidEnrollmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<MDMWebService.AndroidEnrollmentResponse> AndroidEnrollmentAsync(string sContent)
        {
            MDMWebService.AndroidEnrollmentRequest inValue = new MDMWebService.AndroidEnrollmentRequest();
            inValue.Body = new MDMWebService.AndroidEnrollmentRequestBody();
            inValue.Body.sContent = sContent;
            return ((MDMWebService.MDMWebServiceSoap)(this)).AndroidEnrollmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MDMWebService.AndroidDeviceInfoResponse> MDMWebService.MDMWebServiceSoap.AndroidDeviceInfoAsync(MDMWebService.AndroidDeviceInfoRequest request)
        {
            return base.Channel.AndroidDeviceInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MDMWebService.AndroidDeviceInfoResponse> AndroidDeviceInfoAsync(string sContent)
        {
            MDMWebService.AndroidDeviceInfoRequest inValue = new MDMWebService.AndroidDeviceInfoRequest();
            inValue.Body = new MDMWebService.AndroidDeviceInfoRequestBody();
            inValue.Body.sContent = sContent;
            return ((MDMWebService.MDMWebServiceSoap)(this)).AndroidDeviceInfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MDMWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MDMWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MDMWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.5/MDMWebService/MDMWebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MDMWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.5/MDMWebService/MDMWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MDMWebServiceSoap,
            
            MDMWebServiceSoap12,
        }
    }
}
