//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.iOS.Business.BusinessLogics.MDM_Profile;

using System.Data.Entity.Infrastructure;
using Alexis.Common;
using Dashboard.Common.Business.Component.Cryptography;
using MDM.iOS.Business.BusinessLogics.MDM_Profile.BankIslamEn;
using Microsoft.EntityFrameworkCore;

public class BankIslamEntities : DbContext
{
    //public BankIslamEntities()
    //    : base("name=BankIslamEntities")
    //{
    //}

    public BankIslamEntities() : base(GetOptions())
    {
    }

    private static DbContextOptions<BankIslamEntities> GetOptions()
    {
        var optionsBuilder = new DbContextOptionsBuilder<BankIslamEntities>();
        optionsBuilder.UseSqlServer(MsgSec.DecryptString(ConfigHelper.GetConnectionString("connectionString")));
        return optionsBuilder.Options;
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
    }


    public DbSet<MDM_Profile> MDM_Profile { get; set; }
    public DbSet<MDM_Profile_Cellular> MDM_Profile_Cellular { get; set; }
    public DbSet<MDM_Profile_Passcode> MDM_Profile_Passcode { get; set; }
    public DbSet<MDM_Profile_Restriction> MDM_Profile_Restriction { get; set; }
    public DbSet<MDM_Profile_Restriction_Advance> MDM_Profile_Restriction_Advance { get; set; }
    public DbSet<MDM_Profile_VPN> MDM_Profile_VPN { get; set; }
    public DbSet<MDM_Profile_WIFI> MDM_Profile_WIFI { get; set; }
    public DbSet<User_Branch> User_Branch { get; set; }
    public DbSet<MDM_HttpProxy> MDM_HttpProxy { get; set; }
    public DbSet<MDM_Profile_General> MDM_Profile_General { get; set; }
    public DbSet<MDM_Profile_General_BranchID> MDM_Profile_General_BranchID { get; set; }
    public DbSet<MDM_Restriction_Menu> MDM_Restriction_Menu { get; set; }







    //public DbSet<MDM_Profile_LDAP> MDM_Profile_LDAP { get; set; }
    //public DbSet<MDM_Profile_LDAP_SearchSettings> MDM_Profile_LDAP_SearchSettings { get; set; }
}
