//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S_Series_Dashboard.File_Pass {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="File_Pass.File_PassSoap")]
    public interface File_PassSoap {
        
        // CODEGEN: Generating message contract since element name my_MDM_FilePass from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Plist_Pass", ReplyAction="*")]
        S_Series_Dashboard.File_Pass.Plist_PassResponse Plist_Pass(S_Series_Dashboard.File_Pass.Plist_PassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Plist_Pass", ReplyAction="*")]
        System.Threading.Tasks.Task<S_Series_Dashboard.File_Pass.Plist_PassResponse> Plist_PassAsync(S_Series_Dashboard.File_Pass.Plist_PassRequest request);
        
        // CODEGEN: Generating message contract since element name my_MDM_FilePass from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppAndPlist_Pass", ReplyAction="*")]
        S_Series_Dashboard.File_Pass.AppAndPlist_PassResponse AppAndPlist_Pass(S_Series_Dashboard.File_Pass.AppAndPlist_PassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppAndPlist_Pass", ReplyAction="*")]
        System.Threading.Tasks.Task<S_Series_Dashboard.File_Pass.AppAndPlist_PassResponse> AppAndPlist_PassAsync(S_Series_Dashboard.File_Pass.AppAndPlist_PassRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Plist_PassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Plist_Pass", Namespace="http://tempuri.org/", Order=0)]
        public S_Series_Dashboard.File_Pass.Plist_PassRequestBody Body;
        
        public Plist_PassRequest() {
        }
        
        public Plist_PassRequest(S_Series_Dashboard.File_Pass.Plist_PassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Plist_PassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MDM.iOS.Business.BusinessLogics.MDM_Profile.File_Pass.En_MDM_FilePass my_MDM_FilePass;
        
        public Plist_PassRequestBody() {
        }
        
        public Plist_PassRequestBody(MDM.iOS.Business.BusinessLogics.MDM_Profile.File_Pass.En_MDM_FilePass my_MDM_FilePass) {
            this.my_MDM_FilePass = my_MDM_FilePass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Plist_PassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Plist_PassResponse", Namespace="http://tempuri.org/", Order=0)]
        public S_Series_Dashboard.File_Pass.Plist_PassResponseBody Body;
        
        public Plist_PassResponse() {
        }
        
        public Plist_PassResponse(S_Series_Dashboard.File_Pass.Plist_PassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Plist_PassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Plist_PassResult;
        
        public Plist_PassResponseBody() {
        }
        
        public Plist_PassResponseBody(bool Plist_PassResult) {
            this.Plist_PassResult = Plist_PassResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AppAndPlist_PassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AppAndPlist_Pass", Namespace="http://tempuri.org/", Order=0)]
        public S_Series_Dashboard.File_Pass.AppAndPlist_PassRequestBody Body;
        
        public AppAndPlist_PassRequest() {
        }
        
        public AppAndPlist_PassRequest(S_Series_Dashboard.File_Pass.AppAndPlist_PassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AppAndPlist_PassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MDM.iOS.Business.BusinessLogics.MDM_Profile.File_Pass.En_MDM_FilePass my_MDM_FilePass;
        
        public AppAndPlist_PassRequestBody() {
        }
        
        public AppAndPlist_PassRequestBody(MDM.iOS.Business.BusinessLogics.MDM_Profile.File_Pass.En_MDM_FilePass my_MDM_FilePass) {
            this.my_MDM_FilePass = my_MDM_FilePass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AppAndPlist_PassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AppAndPlist_PassResponse", Namespace="http://tempuri.org/", Order=0)]
        public S_Series_Dashboard.File_Pass.AppAndPlist_PassResponseBody Body;
        
        public AppAndPlist_PassResponse() {
        }
        
        public AppAndPlist_PassResponse(S_Series_Dashboard.File_Pass.AppAndPlist_PassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AppAndPlist_PassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AppAndPlist_PassResult;
        
        public AppAndPlist_PassResponseBody() {
        }
        
        public AppAndPlist_PassResponseBody(bool AppAndPlist_PassResult) {
            this.AppAndPlist_PassResult = AppAndPlist_PassResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface File_PassSoapChannel : S_Series_Dashboard.File_Pass.File_PassSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class File_PassSoapClient : System.ServiceModel.ClientBase<S_Series_Dashboard.File_Pass.File_PassSoap>, S_Series_Dashboard.File_Pass.File_PassSoap {
        
        public File_PassSoapClient() {
        }
        
        public File_PassSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public File_PassSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public File_PassSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public File_PassSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        S_Series_Dashboard.File_Pass.Plist_PassResponse S_Series_Dashboard.File_Pass.File_PassSoap.Plist_Pass(S_Series_Dashboard.File_Pass.Plist_PassRequest request) {
            return base.Channel.Plist_Pass(request);
        }
        
        public bool Plist_Pass(MDM.iOS.Business.BusinessLogics.MDM_Profile.File_Pass.En_MDM_FilePass my_MDM_FilePass) {
            S_Series_Dashboard.File_Pass.Plist_PassRequest inValue = new S_Series_Dashboard.File_Pass.Plist_PassRequest();
            inValue.Body = new S_Series_Dashboard.File_Pass.Plist_PassRequestBody();
            inValue.Body.my_MDM_FilePass = my_MDM_FilePass;
            S_Series_Dashboard.File_Pass.Plist_PassResponse retVal = ((S_Series_Dashboard.File_Pass.File_PassSoap)(this)).Plist_Pass(inValue);
            return retVal.Body.Plist_PassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<S_Series_Dashboard.File_Pass.Plist_PassResponse> S_Series_Dashboard.File_Pass.File_PassSoap.Plist_PassAsync(S_Series_Dashboard.File_Pass.Plist_PassRequest request) {
            return base.Channel.Plist_PassAsync(request);
        }
        
        public System.Threading.Tasks.Task<S_Series_Dashboard.File_Pass.Plist_PassResponse> Plist_PassAsync(MDM.iOS.Business.BusinessLogics.MDM_Profile.File_Pass.En_MDM_FilePass my_MDM_FilePass) {
            S_Series_Dashboard.File_Pass.Plist_PassRequest inValue = new S_Series_Dashboard.File_Pass.Plist_PassRequest();
            inValue.Body = new S_Series_Dashboard.File_Pass.Plist_PassRequestBody();
            inValue.Body.my_MDM_FilePass = my_MDM_FilePass;
            return ((S_Series_Dashboard.File_Pass.File_PassSoap)(this)).Plist_PassAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        S_Series_Dashboard.File_Pass.AppAndPlist_PassResponse S_Series_Dashboard.File_Pass.File_PassSoap.AppAndPlist_Pass(S_Series_Dashboard.File_Pass.AppAndPlist_PassRequest request) {
            return base.Channel.AppAndPlist_Pass(request);
        }
        
        public bool AppAndPlist_Pass(MDM.iOS.Business.BusinessLogics.MDM_Profile.File_Pass.En_MDM_FilePass my_MDM_FilePass) {
            S_Series_Dashboard.File_Pass.AppAndPlist_PassRequest inValue = new S_Series_Dashboard.File_Pass.AppAndPlist_PassRequest();
            inValue.Body = new S_Series_Dashboard.File_Pass.AppAndPlist_PassRequestBody();
            inValue.Body.my_MDM_FilePass = my_MDM_FilePass;
            S_Series_Dashboard.File_Pass.AppAndPlist_PassResponse retVal = ((S_Series_Dashboard.File_Pass.File_PassSoap)(this)).AppAndPlist_Pass(inValue);
            return retVal.Body.AppAndPlist_PassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<S_Series_Dashboard.File_Pass.AppAndPlist_PassResponse> S_Series_Dashboard.File_Pass.File_PassSoap.AppAndPlist_PassAsync(S_Series_Dashboard.File_Pass.AppAndPlist_PassRequest request) {
            return base.Channel.AppAndPlist_PassAsync(request);
        }
        
        public System.Threading.Tasks.Task<S_Series_Dashboard.File_Pass.AppAndPlist_PassResponse> AppAndPlist_PassAsync(MDM.iOS.Business.BusinessLogics.MDM_Profile.File_Pass.En_MDM_FilePass my_MDM_FilePass) {
            S_Series_Dashboard.File_Pass.AppAndPlist_PassRequest inValue = new S_Series_Dashboard.File_Pass.AppAndPlist_PassRequest();
            inValue.Body = new S_Series_Dashboard.File_Pass.AppAndPlist_PassRequestBody();
            inValue.Body.my_MDM_FilePass = my_MDM_FilePass;
            return ((S_Series_Dashboard.File_Pass.File_PassSoap)(this)).AppAndPlist_PassAsync(inValue);
        }
    }
}
