name: Mirror Repository

on:
  push:
    branches: [ main, master ]  # Triggers on push to these branches
    tags:                       # Optional: mirror tags as well
      - '*'

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the source code
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches all history for all branches/tags

      # Step 2: Configure git with proper credentials
      - name: Configure Git
        run: |
          git config --global user.name "rohitemerico"
          git config --global user.email "rohit@emerico.com"
          
      # Step 3: Push to destination repository
      - name: Push to destination
        run: |
          git remote add destination https://${{ secrets.DESTINATION_USERNAME }}:${{ secrets.DESTINATION_TOKEN }}@github.com/${{ secrets.DESTINATION_REPO }}.git
          git push destination --all  # Push all branches
          git push destination --tags # Push all tags
