name: Mirror Repository

on:
  push:
    branches:
      - master  # Adjust if your default branch is different

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the source repo as a mirror
        run: |
          git clone --mirror https://github.com/rohitemerico/AlexisDotNet9.git
          cd AlexisDotNet9.git
          git remote add mirror https://x-access-token:${{ secrets.DESTINATION_TOKEN }}@github.com/rohitemerico/AlexisDotNet9UAT.git
          git push --mirror mirror

